#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"

usage() {
  echo "Usage: $0 <company-name> <agent-name>"
  echo ""
  echo "Hires (starts) an agent by opening a new tmux pane with Claude Code."
  echo "The agent directory and CLAUDE.md must already exist."
  exit 1
}

if [[ $# -lt 2 ]]; then
  usage
fi

COMPANY_NAME="$1"
AGENT_NAME="$2"
COMPANY_DIR="$AGENTLATTICE_HOME/$COMPANY_NAME"
AGENT_DIR="$COMPANY_DIR/agents/$AGENT_NAME"

# Validate company exists
if [[ ! -d "$COMPANY_DIR" ]]; then
  echo "Error: Company '$COMPANY_NAME' does not exist at $COMPANY_DIR"
  exit 1
fi

# Create agent directory structure if it doesn't exist
if [[ ! -d "$AGENT_DIR" ]]; then
  mkdir -p "$AGENT_DIR/.claude/skills" "$AGENT_DIR/workspace" "$AGENT_DIR/memory"
  echo "Created agent directory at $AGENT_DIR"
fi

# CLAUDE.md must exist (generated by the management console before calling this script)
if [[ ! -f "$AGENT_DIR/CLAUDE.md" ]]; then
  echo "Error: Agent '$AGENT_NAME' has no CLAUDE.md at $AGENT_DIR/CLAUDE.md"
  echo "Generate the agent's CLAUDE.md before running this script."
  exit 1
fi

# Check tmux is available
if ! command -v tmux &> /dev/null; then
  echo "Error: tmux is not installed. Install it with: brew install tmux"
  exit 1
fi

# Check we're inside a tmux session
if [[ -z "${TMUX:-}" ]]; then
  echo "Error: Not inside a tmux session. Start tmux first: tmux new -s agentlattice"
  exit 1
fi

# Get loop interval from config
LOOP_INTERVAL=$(config_get "default_loop_interval" "5m")

# Open a new tmux pane and start claude with /loop
tmux split-window -h "cd '$AGENT_DIR' && claude \"/loop $LOOP_INTERVAL あなたのタスクを実行して\""

echo "Agent '$AGENT_NAME' hired successfully in company '$COMPANY_NAME'."
echo "A new tmux pane has been opened with Claude Code in $AGENT_DIR"
echo "Auto-started /loop with interval $LOOP_INTERVAL"
