#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/common.sh"

usage() {
  echo "Usage: $0 <company-name> <agent-name>"
  echo ""
  echo "Hires (starts) an agent by opening a new tmux pane with Claude Code."
  echo "The agent directory and CLAUDE.md must already exist."
  exit 1
}

if [[ $# -lt 2 ]]; then
  usage
fi

COMPANY_NAME="$1"
AGENT_NAME="$2"
COMPANY_DIR="$AGENTLATTICE_HOME/$COMPANY_NAME"
AGENT_DIR="$COMPANY_DIR/agents/$AGENT_NAME"

# Validate company exists
if [[ ! -d "$COMPANY_DIR" ]]; then
  echo "Error: Company '$COMPANY_NAME' does not exist at $COMPANY_DIR"
  exit 1
fi

# Create agent directory structure if it doesn't exist
if [[ ! -d "$AGENT_DIR" ]]; then
  mkdir -p "$AGENT_DIR/.claude/skills" "$AGENT_DIR/workspace" "$AGENT_DIR/memory"
  echo "Created agent directory at $AGENT_DIR"
fi

# CLAUDE.md must exist (generated by the management console before calling this script)
if [[ ! -f "$AGENT_DIR/CLAUDE.md" ]]; then
  echo "Error: Agent '$AGENT_NAME' has no CLAUDE.md at $AGENT_DIR/CLAUDE.md"
  echo "Generate the agent's CLAUDE.md before running this script."
  exit 1
fi

# Check tmux is available
if ! command -v tmux &> /dev/null; then
  echo "Error: tmux is not installed. Install it with: brew install tmux"
  exit 1
fi

# Check we're inside a tmux session
if [[ -z "${TMUX:-}" ]]; then
  echo "Error: Not inside a tmux session. Start tmux first: tmux new -s agentlattice"
  exit 1
fi

# Get config values
LOOP_INTERVAL=$(config_get "default_loop_interval" "5m")
MAX_PANES=$(config_get "max_panes_per_window" "4")

STARTUP_CMD="cd '$AGENT_DIR' && claude \"/loop $LOOP_INTERVAL あなたのタスクを実行して\""

# Get current pane count in the active window
CURRENT_PANES=$(tmux list-panes | wc -l | tr -d ' ')

if [[ "$CURRENT_PANES" -ge "$MAX_PANES" ]]; then
  # Current window is full — create a new window and apply tiled layout there
  tmux new-window "$STARTUP_CMD"
  tmux select-layout tiled
else
  # Split within the current window and re-tile
  tmux split-window -h "$STARTUP_CMD"
  tmux select-layout tiled
fi

echo "Agent '$AGENT_NAME' hired successfully in company '$COMPANY_NAME'."
echo "A new tmux pane has been opened with Claude Code in $AGENT_DIR"
echo "Auto-started /loop with interval $LOOP_INTERVAL"
echo "Layout: tiled (max $MAX_PANES panes per window)"
